insert into product(name, category_id)
values ('Laptop', 1),
       ('Smartphone', 1),
       ('Headphones', 1),
       ('Coffee Maker', 2),
       ('Blender', 2),
       ('Toaster', 2),
       ('Running Shoes', 3),
       ('Yoga Mat', 3),
       ('Dumbbells', 3),
       ('Novel Book', 4),
       ('Cookbook', 4),
       ('Magazine', 4),
       ('Backpack', 5),
       ('Wallet', 5),
       ('Sunglasses', 5),
       ('Gaming Console', 1),
       ('Smart Watch', 1),
       ('Kitchen Scale', 2),
       ('Tennis Racket', 3),
       ('Travel Guide', 4);


insert into hotel(name, rating, description)
values ('Hyatt', 5, 'An awesome hotel'),
       ('Marriott', 4, 'A luxurious stay'),
       ('Hilton', 5, 'Great for business travelers'),
       ('Sheraton', 4, 'Perfect for family vacations'),
       ('Ritz-Carlton', 5, 'A premium experience'),
       ('Holiday Inn', 3, 'Comfortable and affordable'),
       ('Four Seasons', 5, 'Ultimate luxury and service'),
       ('Best Western', 3, 'Convenient and budget-friendly'),
       ('Wyndham', 4, 'An excellent mid-range option'),
       ('InterContinental', 5, 'High-end amenities and service'),
       ('Fairmont', 4, 'Blending luxury with heritage'),
       ('The Westin', 4, 'Wellness-focused accommodations'),
       ('Novotel', 4, 'Modern and versatile for travelers'),
       ('Ibis', 3, 'Affordable and reliable'),
       ('Sofitel', 5, 'French-inspired luxury'),
       ('Mandarin Oriental', 5, 'Elegance and sophistication'),
       ('Radisson', 4, 'Stylish and convenient stays'),
       ('Crowne Plaza', 4, 'Business-focused properties'),
       ('Aloft', 3, 'Trendy and urban hotels'),
       ('St. Regis', 5, 'Timeless elegance at its best'),
       ('The Langham', 5, 'Heritage with a touch of luxury'),
       ('Le Meridien', 4, 'Celebrating culture through design'),
       ('Motel 6', 2, 'Simple and affordable stays');
